rpi_hostname: myraspi

rpi_wpa_supplicant_networks:
  - ssid: "wifi1"
    psk: ""
  - ssid: "wifi2"
    psk: ""

packages_list:
  - git
  - tmux
  - bash
  - vim
  - sudo
  - most
  - make
  - wpasupplicant
  - ufw
  - unattended-upgrades
  - ntp

security_autoupdate_reboot: true
security_autoupdate_reboot_time: "02:00"
security_autoupdate_mail_to: ""
security_autoupdate_mail_only_on_error: true
security_autoupdate_blacklist: []
